### PR TITLE
Update dependencies

### LINKED ISSUE #111: Address npm dependency issues found in master branch
bitHound discovered:

  * 3 packages with at least one security vulnerability.
  * 5 outdated packages.

For details go to [bitHound](https://www.bithound.io/github/donpark/hbs/master/dependencies/npm)

### PR DESCRIPTION
**Pull request by lenovouser**
Closes #111

### CODE REVIEW

**Comment by ApfelUser** [comment]
Hm. After some researching it seems like the error seems to come from something in npm. I think it has nothing really to do with hbs.

**Comment by defunctzombie** [comment]
tests need to pass before this can be merged. Please fix.

**Comment by ApfelUser** [comment]
Apparently this is just a hickup:

[stackoverflow.com/npm-doesnt-work-get-always-this-error-error-cannot-find-module-are-we-there-yet](http://stackoverflow.com/questions/31025048/npm-doesnt-work-get-always-this-error-error-cannot-find-module-are-we-ther)

**Comment by lenovouser** [comment]
Closing this as it seems to be a **npm** problem, and their answers are extremely slow. See https://github.com/npm/npm/issues/8759#issuecomment-150170426

**Pull request closed without merging**
