### PR TITLE
Added multiple views abilities for express@4.12.0

### PR DESCRIPTION
**Pull request by wmonk**
As per issue #60 and the patch from #79, this is an async implementation of multiple view directories supported in strongloop/express#2320

### CODE REVIEW

**Comment by wmonk** [comment]
@defunctzombie is there any capacity to get this merged?

Not sure why the tests broke, look like an issue with Travis that I can't re-run.

**Comment by defunctzombie** [comment]
@wmonk just haven't had the time to review yet. Will try to get to it this week. Please ping me again if I haven't reviewed by next week.

**Comment by wmonk** [comment]
@defunctzombie no problem! Thanks for up keeping such a useful module!

**Comment by defunctzombie** [comment]
Tests are failing.

**Comment by wmonk** [comment]
Not sure why seems to be an issue with npm install not the code?

**Comment by defunctzombie** [comment]
```Error: listen EADDRINUSE``` That is the error I see. npm install works fine on my end.

**Comment by defunctzombie** [comment]
oh nvm, my issue was a local one. Yea, the npm install is a 0.8 issue.

**Comment by defunctzombie** [comment]
`^` is not supported by the npm version shipped with 0.8, not an issue with this PR.

**Pull request merged**
