### PR TITLE
support params for async helper

### PR DESCRIPTION
**Pull request by draconisNoctis**

### CODE REVIEW

**Comment by defunctzombie** [comment]
can you describe what this is for/what it does please

**Comment by draconisNoctis** [comment]
It passes all given parameters (and the context) to the registered async helper, just like the synchronous helper does.

Previously, only one parameter was passed (or the context, if no parameters was set). So you couldn't use an async helper with more than one parameter (or parameter(s) + context).

**Comment by defunctzombie** [comment]
Any thoughts on why the tests are failing? The code looks good to me but failing CI concerns me. Should we just remove the express 3 checks and just stick with 4 now?

**Comment by defunctzombie** [comment]
I updated/fixed the tests on master so if you rebase those should get fixed up.

**Comment by draconisNoctis** [comment]
I rebased my fork, CI shouldn't fail anymore.

**Pull request merged**
